name: Build SecureVault2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSVC (Visual Studio Compiler)
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile SecureVault2
      run: |
        cl /MT /O2 /GS /sdl main.cpp bcrypt.lib advapi32.lib user32.lib gdi32.lib comdlg32.lib shell32.lib /Fe:SecureVault2.exe /link /NXCOMPAT /DYNAMICBASE /SUBSYSTEM:WINDOWS

    - name: Upload the EXE
      uses: actions/upload-artifact@v4
      with:
        name: SecureVault2-Executable
        path: SecureVault2.exe
        
